---
title: "Survivor Inspiration Network"
author: "Jaren Brownlee"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
library(tidyverse)
library(survivoR)
library(igraph)
```

```{r load_data}
# self-comparisons
selfCompare <- read_csv("./selfCompare.csv", show_col_types = FALSE) %>% 
  select(-c(gender)) %>% fill(season) %>%
  pivot_longer(3:9, values_to="inspiration") %>% select(-c(name)) %>%
  filter(!is.na(inspiration)) %>%
  separate(inspiration, into = c('inspFirst', 'inspLast'),
           sep=" ", extra="merge", remove=FALSE)

# top seasons from reddit
reddit <- read_csv("./season_census.csv", show_col_types = FALSE) %>%
  mutate(season = str_c("US",sprintf("%02d",season)))
```

## Data Wrangling

```{r tidy_names}
fullNames <- castaway_details %>% 
  merge((castaways %>% select(c(castaway_id, version_season))), 
        by="castaway_id") %>%
  mutate(full_name = case_when(
    castaway_id == "US0281" ~ "JT Thomas", 
    castaway_id == "US0029" ~ "Elisabeth Hasselbeck",
    TRUE ~ full_name)) %>%
  separate(full_name, into = c('first','last'), 
    sep = " ", extra = "merge", remove = FALSE) %>%
  mutate(name = case_when(
    str_detect(full_name,short_name) ~ str_c(first, ' ', last),
    TRUE ~ str_c(first, ' "', short_name, '" ', last))) %>%
  select(castaway_id, full_name, first, short_name, last) %>%
  merge((selfCompare %>% select(c(inspiration, inspFirst, inspLast))),
        by.x="last", by.y="inspLast", all=TRUE) %>% unique() %>%
  mutate(inspiration = case_when(
    !is.na(inspiration) ~ inspiration,
    str_detect(short_name, first) ~ full_name,
    short_name == last ~ full_name,
    castaway_id == "US0302" ~ full_name,
    castaway_id == "US0305" ~ "Jimmy Tarantino",
    TRUE ~ str_c(short_name, last, sep=" "))) %>%
  mutate(fullName = case_when(
    is.na(inspFirst) ~ inspiration,
    full_name == inspiration ~ full_name,
    short_name == inspFirst ~ inspiration,
    short_name == "Shan" ~ str_c(short_name, last, sep=" "),
    str_detect(full_name, short_name) ~ full_name,
    TRUE ~ str_c(short_name, last, sep=" "))) %>%
  rename(shortName = short_name) %>%
  left_join(castaways, by="castaway_id") %>% unique() %>%
  mutate(season = substr(version_season,3,4)) %>%
  select(season, castaway_id, first, shortName, last, fullName)
```

``` {r top10_seasons}
# top seasons from github data
topSzns <- tribe_mapping %>% 
  select(version_season, episode, day, tribe_status) %>%
  unique() %>% group_by(version_season) %>% mutate(premier = min(episode)) %>%
  filter(tribe_status == "Merged") %>% mutate(merge = min(episode)) %>%
  filter(day == max(day)) %>% mutate(finale = max(episode)) %>%
  select(version_season, premier, merge, finale) %>% unique() %>%
  merge((viewers %>% select(version_season, episode, imdb_rating)),
        by = "version_season") %>% group_by(version_season) %>%
  filter(episode == merge | episode == finale | episode == premier) %>%
  select(version_season, episode, imdb_rating) %>%
  summarise(pmf_imdb = mean(imdb_rating, na.rm=TRUE)) %>%
  merge((viewers %>% select(version_season, viewers, imdb_rating)),
        by = "version_season") %>% group_by(version_season) %>%
  mutate(tot_viewers = sum(viewers, na.rm=TRUE), 
            avg_imdb = mean(imdb_rating, na.rm=TRUE)) %>%
  select(-c(viewers, imdb_rating)) %>% unique()

# most common seasons across 4 categories:
# total viewers, imdb ratings, premier/merge/finale ratings, reddit ratings
top10s <- tibble((topSzns %>% arrange(desc(tot_viewers)) %>% head(10) %>% 
                  select(version_season) %>% rename(viewers = version_season)),
                (topSzns %>% arrange(desc(pmf_imdb)) %>% head(10) %>% 
                  select(version_season) %>% rename(pmf = version_season)),
                (topSzns %>% arrange(desc(avg_imdb)) %>% head(10) %>% 
                  select(version_season) %>% rename(imdb = version_season)),
                (reddit %>% arrange(desc(percent)) %>% head(10) %>%
                   select(season) %>% rename(reddit = season))) %>%
  pivot_longer(everything(), names_to="source", values_to="season") %>%
  group_by(season) %>% summarise(count = n()) %>% arrange(desc(count)) %>%
  filter(count > 1) %>% head(10) %>% select(season)
```

``` {r placement_details}
# total seasons, total days, highest placement, average placement
stats <- castaways %>% 
  select(version_season, castaway_id, full_name, day, order, jury_status) %>%
  group_by(version_season) %>% mutate(order = max(order) + 1 - order) %>%
  arrange(version_season, order) %>% mutate(day = case_when(
    !(version_season %in% c("US38", "US40")) ~ day,
    is.na(jury_status) ~ day, day >= 35 ~ day, TRUE ~ 35)) %>% ungroup() %>%
  select(-c(jury_status)) %>% group_by(version_season, castaway_id) %>% 
  mutate(order = case_when(n() > 1 ~ min(order), TRUE ~ order),
         day = case_when(n() > 1 ~ max(day), TRUE ~ day)) %>% unique() %>%
  ungroup() %>% group_by(version_season) %>% mutate(order = row_number()) %>%
  ungroup() %>% group_by(castaway_id) %>% 
  mutate(total_seasons=n(), total_days=sum(day), 
         best_place=min(order), avg_place=round(mean(order),2)) %>%
  ungroup() %>% select(-c(day, order, version_season, full_name)) %>% unique()
```

``` {r comparisons}
# gender comparison, last 5 seasons, number of comparisons
comparisons <- selfCompare %>% select(-c(inspFirst, inspLast)) %>% 
  mutate(season = substr(season,8,9)) %>%
  left_join(fullNames,  by=c("season"="season", "castaway"="shortName")) %>%
  rename(cast_name = fullName, cast_id = castaway_id) %>%
  select(cast_id, cast_name, inspiration) %>%
  left_join(fullNames, by=c("inspiration"="fullName")) %>%
  rename(inspo_name = inspiration, inspo_id = castaway_id) %>%
  select(cast_id, cast_name, inspo_id, inspo_name) %>% unique()

details <- castaway_details %>% 
  mutate(gender = case_when(
    castaway_id == "US0598" ~ "Female", TRUE ~ gender
  )) %>% select(castaway_id, gender) %>%
  merge((castaways %>% select(castaway_id, season)), by="castaway_id")

comp_detes <- comparisons %>%
  group_by(inspo_id) %>% mutate(count = n()) %>% ungroup() %>%
  merge(details, by.x = "cast_id", by.y = "castaway_id") %>%
  rename(c_szn = season, c_gender = gender) %>% group_by(cast_id) %>% 
  mutate(c_szn = min(c_szn)) %>% unique() %>% ungroup() %>% 
  merge(details, by.x = "inspo_id", by.y = "castaway_id") %>%
  rename(i_szn = season, i_gender = gender) %>% group_by(inspo_id, cast_id) %>% 
  mutate(i_szn = max(i_szn[i_szn < c_szn]),
         past5 = case_when(c_szn - i_szn <= 5 ~ TRUE, TRUE ~ FALSE),
         gender = case_when(c_gender == i_gender ~ TRUE, TRUE ~ FALSE)) %>%
  select(cast_id, inspo_id, inspo_name, count, past5, gender) %>% 
  unique() %>% ungroup()
```

``` {r unlinked}
unlinked <- comparisons %>% 
  group_by(inspo_id) %>% mutate(i_pop = n()) %>% ungroup() %>%
  group_by(cast_id) %>% mutate(c_pop = n()) %>%
  mutate(unpopular = (c_pop == sum(i_pop)),
         inspo_cast = (inspo_id %in% comparisons$cast_id),
         cast_inspo = (cast_id %in% comparisons$inspo_id)) %>%
  filter(unpopular & !inspo_cast & !cast_inspo) %>% select(1:4)
```

``` {r link_tree}
net_df <- comparisons %>% filter(!(inspo_id %in% unlinked$inspo_id))

link_tree <- net_df %>% 
  rename(id0 = cast_id, name0 = cast_name, 
         id1 = inspo_id, name1 = inspo_name) %>%
  left_join((net_df %>% select(-c(cast_name))), by=c("id1" = "cast_id")) %>% 
  rename(id2 = inspo_id, name2 = inspo_name) %>%
  left_join((net_df %>% select(-c(cast_name))), by=c("id2" = "cast_id")) %>%
  rename(id3 = inspo_id, name3 = inspo_name) %>%
  left_join((net_df %>% select(-c(cast_name))), by=c("id3" = "cast_id")) %>%
  rename(id4 = inspo_id, name4 = inspo_name) %>%
  left_join((net_df %>% select(-c(cast_name))), by=c("id4" = "cast_id")) %>%
  rename(id5 = inspo_id, name5 = inspo_name) %>%
  mutate(root = case_when(!is.na(id5) ~ id5, !is.na(id4) ~ id4,
       !is.na(id3) ~ id3, !is.na(id2) ~ id2, TRUE ~ id1)) %>%
  left_join((fullNames %>% select(c(castaway_id, fullName)) %>% unique()),
            by=c("root" = "castaway_id")) %>% unique()

x%>% 
  select(root, fullName, root_count) %>% unique()
```

``` {r prepare_network}
edges <- net_df %>% select(cast_id, inspo_id) %>%
  rename(from = cast_id, to = inspo_id)

nSize <- net_df %>% select(inspo_id, inspo_name) %>%
  group_by(inspo_id) %>% mutate(count = n()) %>%
  select(inspo_id, count) %>% unique() %>% filter(count > 1)

nodes <- net_df %>%
  pivot_longer(everything(), names_to= c("type", "name"), names_sep="_") %>%
  mutate(type = 1:(nrow(net_df)*4), type = case_when(
    type %% 2 == 0 ~ type / 2,
    TRUE ~ as.double(NA))) %>% fill(type, .direction="up") %>%
  pivot_wider(id_cols="type", names_from="name", values_from="value") %>%
  select(-c(type)) %>% unique() %>%
  left_join(nSize, by=c("id"="inspo_id")) %>%
  mutate(scaled = case_when(is.na(count) ~ 0.5, TRUE ~ as.double(count)),
         scaled = log(scaled+1)*2)
```

## Data Visualization

```{r plot_data}
net <- graph_from_data_frame(
  d = edges, vertices = nodes, directed = T
)
net <- igraph::simplify(
  net, remove.multiple=F, remove.loops=T
)
# layout_nicely(net), layout_with_dh(net),
# layout_with_gem(net), layout_with_kk(net)
plot(net, 
     edge.arrow.size=0, 
     edge.size=0.01,
     vertex.label=NA,
     vertex.size=V(net)$scaled,
     # vertex.size=3,
     layout=layout_with_kk(net))
```
